### ISSUE TITLE
Créer des features

### ISSUE THREAD

**Issue by ghost** [mmibordeaux/workshop#2]
Les projets ont des caractéristiques (features). Plus un projet répond à des caractéristiques, mieux c'est. 

Une caractéristique n'est jamais acquise définitivement : elle doit être actualisée régulièrement pour continuer à caractériser le projet. Par exemple : un projet débloque la caractéristique "Pertinence du nom". La caractéristique est alors à son maximum. Le lendemain ou le surlendemain, elle a baissé, et les étudiants doivent valider à nouveau que le nom de leur projet est toujours pertinent. Cela permet de rappeler aux étudiants que ces questions (est-ce que mon projet utilise des microformats ? est-il valide w3c ? son nom est-il pertinent ?) doivent être posées régulièrement dans une phase de prototypage car un projet peut évoluer, changer de périmètre, etc.

**Comment by arnaudlevy** [comment]
Features ou achievements?

**Comment by korasaccharin** [comment]
Pour moi, "achievement" correspond à la forme (ce que les étudiants doivent faire) et "feature" au fond (ce que ces questions supposent pour les projets). Donc je penche pour "feature".

Sommes-nous d'accord sur le fonctionnement ?

**Comment by arnaudlevy** [comment]
oui !

**Comment by arnaudlevy** [comment]
J'ai créé l'objet, mais pas le habtm

**Comment by korasaccharin** [comment]
Vraiment ? Il me semble que c'est fait.
