### ISSUE TITLE
Open Badges ???

### ISSUE THREAD

**Issue by arnaudlevy** [mmibordeaux/workshop#5]
http://openbadges.org/

Pour les faire : 
https://www.openbadges.me/

Pour les délivrer : 
https://github.com/PRX/badges_engine
https://github.com/eldwin/openbadges-rails

Pas directement intéressant je crois : 
https://github.com/mozilla/openbadges-backpack

**Comment by korasaccharin** [comment]
Intéressant !

Par contre, il y a à peine une centaine de lignes dans ces plugins. Vu les dates de mises à jour, je penche pour faire nous-même le moteur pour les délivrer. Qu'en penses-tu ?


![screen shot 2016-01-15 at 10 44 21](https://cloud.githubusercontent.com/assets/919852/12350116/40745aa6-bb75-11e5-9e08-c93f8f6d432b.png)
![screen shot 2016-01-15 at 10 44 17](https://cloud.githubusercontent.com/assets/919852/12350118/44c45548-bb75-11e5-80ba-5f7f9e827135.png)
